# -*- coding: utf-8 -*-
"""PROJECT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sk6-wi0-SYXOAbIO4mkuTXKQaEt8h6Xz
"""

Student_name=input("Enter your name")
print(Student_name)
maths = int(input("Enter your marks in Maths : "))
coa =int(input("Enter your marks in Coa : "))
tafl = int(input("Enter your marks in Tafl : "))
os = int(input("Enter your marks in OS : "))
dstl = int(input("Enter your marks in DSTL : "))
total = (maths+coa+tafl+os+dstl)
result = total/500 *100
print(f"Your gpa is {result/9.5} ")

dict = {"maths":maths , "coa":coa, "tafl":tafl, "os":os, "dstl":dstl}
for i in dict.keys():
  marks = dict[i]
  if marks>=80:
    print(f"{i}-->A")
  elif marks>=60:
    print(f"{i}-->B")
  elif marks>=50:
    print(f"{i}-->C")
  elif marks>=40:
    print(f"{i}-->D")
  else:
    print(f"{i}-->F")